"""
CreditMemoGenerator — generates credit memo narrative using LLM + deterministic ratios.

Architecture:
  - Ratio calculations are INJECTED from ratios.py (deterministic code)
  - LLM generates ONLY narrative sections (borrower profile, risk assessment, recommendation)
  - Financial tables are built from code, never from LLM output
  - Source attributions are required for every factual claim

This enforces the CLAUDE.md rule:
    "Ratio calculations are CODE, not LLM — never let the LLM calculate EBITDA margins"
"""

from __future__ import annotations

import json
import logging
from decimal import Decimal
from typing import Any

import anthropic

from app.core.config import get_settings
from app.pipelines.generation.ratios import calculate_ratios, ratios_to_display_dict

logger = logging.getLogger(__name__)

_MAX_TOKENS = 3000

_SYSTEM_PROMPT = """You are a senior credit analyst at a UK advisory firm.

You are generating narrative sections for a credit memorandum.

CRITICAL RULES:
1. Only generate the NARRATIVE sections (borrower profile, risk assessment, recommendation).
2. Do NOT generate or modify any financial figures, ratios, or tables — these are injected separately.
3. Reference provided financial data to support your narrative but NEVER calculate ratios yourself.
4. Every claim about the company must reference the provided financial data or source documents.
5. Use professional, formal UK financial advisory language.
6. Flag any data gaps or inconsistencies explicitly.
7. The recommendation must be supported by specific evidence from the financial data.

Structure your output as valid JSON with these exact keys:
{
  "borrower_profile": "...",
  "financial_overview": "...",
  "risk_assessment": "...",
  "mitigating_factors": "...",
  "recommendation": "...",
  "conditions_precedent": "..."
}"""


class CreditMemoGenerator:
    """
    Generates credit memo documents with LLM narrative + code-calculated ratios.

    Usage::

        generator = CreditMemoGenerator(api_key=settings.anthropic_api_key)
        memo = await generator.generate(
            company_name="Acme Ltd",
            financials_data=[{...}, {...}],
            ratios=calculated_ratios_dict,
            comparables=[...],
        )
    """

    def __init__(self, api_key: str) -> None:
        self._api_key = api_key
        self._client = anthropic.AsyncAnthropic(api_key=api_key)
        self._settings = get_settings()

    async def generate(
        self,
        company_name: str,
        financials_data: list[dict[str, Any]],
        ratios: dict[str, Any],
        comparables: list[dict[str, Any]] | None = None,
    ) -> dict[str, Any]:
        """
        Generate a structured credit memo.

        Args:
            company_name:    Target company name.
            financials_data: List of financial period dicts (from FinancialStatement rows).
                             Each dict has: period_end, revenue, ebitda, net_income, etc.
            ratios:          Pre-calculated ratios dict from calculate_ratios().
                             These are INJECTED into the output, not generated by LLM.
            comparables:     Optional list of comparable company dicts for benchmarking.

        Returns:
            {
                "company_name": str,
                "sections": {
                    "borrower_profile": str,
                    "financial_overview": str,
                    "risk_assessment": str,
                    "mitigating_factors": str,
                    "recommendation": str,
                    "conditions_precedent": str,
                },
                "financial_tables": {
                    "income_statement": [...],   # structured rows, code-generated
                    "key_ratios": {...},          # code-calculated, display formatted
                },
                "sources": [...],
                "model_used": str,
                "prompt_tokens": int,
                "completion_tokens": int,
                "generation_cost_usd": float,
            }
        """
        # ------------------------------------------------------------------
        # Build the deterministic financial tables (never from LLM)
        # ------------------------------------------------------------------
        financial_tables = self._build_financial_tables(financials_data, ratios)

        # ------------------------------------------------------------------
        # Build the prompt context
        # ------------------------------------------------------------------
        context = self._build_prompt_context(
            company_name=company_name,
            financials_data=financials_data,
            ratios=ratios,
            financial_tables=financial_tables,
            comparables=comparables,
        )

        # ------------------------------------------------------------------
        # LLM generates ONLY narrative text
        # ------------------------------------------------------------------
        response = await self._client.messages.create(
            model=self._settings.llm_model,
            max_tokens=_MAX_TOKENS,
            temperature=0.3,
            system=_SYSTEM_PROMPT,
            messages=[
                {
                    "role": "user",
                    "content": context,
                }
            ],
        )

        raw_text = response.content[0].text.strip()
        sections = self._parse_sections(raw_text)

        # ------------------------------------------------------------------
        # Calculate generation cost (approximate)
        # ------------------------------------------------------------------
        prompt_tokens = response.usage.input_tokens
        completion_tokens = response.usage.output_tokens
        # Approximate cost tracking (varies by model)
        cost_usd = (prompt_tokens * 0.000003) + (completion_tokens * 0.000015)

        return {
            "company_name": company_name,
            "sections": sections,
            "financial_tables": financial_tables,
            "sources": [
                {"type": "financial_data", "description": "Provided financial statements"},
            ],
            "model_used": self._settings.llm_model,
            "prompt_tokens": prompt_tokens,
            "completion_tokens": completion_tokens,
            "generation_cost_usd": round(cost_usd, 6),
        }

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _build_financial_tables(
        self,
        financials_data: list[dict[str, Any]],
        ratios: dict[str, Any],
    ) -> dict[str, Any]:
        """
        Build structured financial tables from deterministic data.
        These are NEVER generated by the LLM.
        """
        income_rows = []
        for period in sorted(financials_data, key=lambda x: x.get("period_end", ""), reverse=True):
            income_rows.append(
                {
                    "period": str(period.get("period_end", "N/A")),
                    "revenue": _fmt_currency(period.get("revenue")),
                    "gross_profit": _fmt_currency(period.get("gross_profit")),
                    "ebitda": _fmt_currency(period.get("ebitda")),
                    "net_income": _fmt_currency(period.get("net_income")),
                    "net_debt": _fmt_currency(period.get("net_debt")),
                }
            )

        # Display-formatted ratios from code calculations
        display_ratios = ratios_to_display_dict(
            {k: Decimal(str(v)) if v is not None else None for k, v in ratios.items()}
        )

        return {
            "income_statement": income_rows,
            "key_ratios": display_ratios,
        }

    def _build_prompt_context(
        self,
        company_name: str,
        financials_data: list[dict[str, Any]],
        ratios: dict[str, Any],
        financial_tables: dict[str, Any],
        comparables: list[dict[str, Any]] | None,
    ) -> str:
        lines = [
            f"Generate a credit memorandum for: {company_name}",
            "",
            "=== FINANCIAL SUMMARY (code-calculated, do not modify) ===",
        ]

        # Key ratios summary
        for key, val in financial_tables["key_ratios"].items():
            lines.append(f"  {key.replace('_', ' ').title()}: {val}")

        lines.append("")
        lines.append("=== INCOME STATEMENT DATA ===")
        for row in financial_tables["income_statement"]:
            lines.append(
                f"  {row['period']}: Revenue {row['revenue']}, EBITDA {row['ebitda']}, "
                f"Net Income {row['net_income']}, Net Debt {row['net_debt']}"
            )

        if comparables:
            lines.append("")
            lines.append("=== COMPARABLE COMPANIES ===")
            for comp in comparables[:5]:
                lines.append(
                    f"  {comp.get('name', 'N/A')} ({comp.get('ticker', 'N/A')}): "
                    f"EV/EBITDA {comp.get('ev_ebitda', 'N/A')}x, "
                    f"EV/Revenue {comp.get('ev_revenue', 'N/A')}x"
                )

        lines.append("")
        lines.append(
            "Generate the narrative sections. "
            "Reference the above data to support your analysis. "
            "Return valid JSON only."
        )

        return "\n".join(lines)

    def _parse_sections(self, raw_text: str) -> dict[str, str]:
        """Parse the LLM's JSON output into section strings."""
        # Strip markdown code fences if present
        text = raw_text
        if text.startswith("```"):
            text = text.split("```")[1]
            if text.startswith("json"):
                text = text[4:]
            text = text.strip()

        try:
            data = json.loads(text)
            return {
                "borrower_profile": data.get("borrower_profile", ""),
                "financial_overview": data.get("financial_overview", ""),
                "risk_assessment": data.get("risk_assessment", ""),
                "mitigating_factors": data.get("mitigating_factors", ""),
                "recommendation": data.get("recommendation", ""),
                "conditions_precedent": data.get("conditions_precedent", ""),
            }
        except json.JSONDecodeError:
            logger.warning("Credit memo LLM returned non-JSON — using raw text as fallback")
            return {
                "borrower_profile": raw_text,
                "financial_overview": "",
                "risk_assessment": "",
                "mitigating_factors": "",
                "recommendation": "",
                "conditions_precedent": "",
            }


def _fmt_currency(value: Any) -> str:
    """Format a currency value as a string with GBP sign."""
    if value is None:
        return "N/A"
    try:
        d = Decimal(str(value))
        return f"£{int(d):,}"
    except Exception:
        return str(value)
