"""Financial statement schemas with computed metrics.

All ratio calculations are done in code here — never delegated to the LLM.
"""

from __future__ import annotations

import uuid
from datetime import date, datetime
from decimal import Decimal

from pydantic import BaseModel, ConfigDict, Field, computed_field, model_validator

from app.schemas.common import PageMeta


class FinancialStatementResponse(BaseModel):
    """Full normalized financial statement for a single period.

    Computed metrics (ebitda_margin, net_margin, leverage_ratio) are derived
    deterministically in Python — not generated by the LLM.
    """

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    company_id: uuid.UUID
    period_start: date | None
    period_end: date
    currency: str = "GBP"

    # Income statement
    revenue: Decimal | None
    cost_of_sales: Decimal | None
    gross_profit: Decimal | None
    ebitda: Decimal | None
    operating_profit: Decimal | None
    net_income: Decimal | None

    # Balance sheet
    total_assets: Decimal | None
    total_liabilities: Decimal | None
    net_debt: Decimal | None
    equity: Decimal | None

    # Cash flow
    cash_from_operations: Decimal | None
    capex: Decimal | None
    free_cash_flow: Decimal | None

    created_at: datetime
    updated_at: datetime

    # Computed fields — all deterministic Python, no LLM
    @computed_field  # type: ignore[misc]
    @property
    def ebitda_margin(self) -> Decimal | None:
        """EBITDA / Revenue — deterministic calculation."""
        if self.ebitda is not None and self.revenue and self.revenue != 0:
            return (self.ebitda / self.revenue * 100).quantize(Decimal("0.01"))
        return None

    @computed_field  # type: ignore[misc]
    @property
    def net_margin(self) -> Decimal | None:
        """Net Income / Revenue — deterministic calculation."""
        if self.net_income is not None and self.revenue and self.revenue != 0:
            return (self.net_income / self.revenue * 100).quantize(Decimal("0.01"))
        return None

    @computed_field  # type: ignore[misc]
    @property
    def leverage_ratio(self) -> Decimal | None:
        """Net Debt / EBITDA — deterministic calculation."""
        if self.net_debt is not None and self.ebitda and self.ebitda != 0:
            return (self.net_debt / self.ebitda).quantize(Decimal("0.01"))
        return None

    @computed_field  # type: ignore[misc]
    @property
    def gross_margin(self) -> Decimal | None:
        """Gross Profit / Revenue — deterministic calculation."""
        if self.gross_profit is not None and self.revenue and self.revenue != 0:
            return (self.gross_profit / self.revenue * 100).quantize(Decimal("0.01"))
        return None


class FinancialSummary(BaseModel):
    """Lightweight summary for embedding in other responses (deals, companies)."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    company_id: uuid.UUID
    period_end: date
    currency: str
    revenue: Decimal | None
    ebitda: Decimal | None
    net_income: Decimal | None
    net_debt: Decimal | None
    ebitda_margin: Decimal | None = None
    net_margin: Decimal | None = None
    leverage_ratio: Decimal | None = None


class FinancialListResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    items: list[FinancialStatementResponse]
    meta: PageMeta
